# 01. Carga y exploración inicial
Objetivo: cargar los datos, inspeccionarlos y listar los problemas detectados.

In [2]:
# Importaciones - Bibliotecas

import pandas as pd
import numpy as np

In [3]:
# Configuración de la visualización

pd.set_option("display.max_columns", None)

In [5]:
# Carga del csv (añadir nombre)
# Cambiar de sito shape y añadir print

df_bank = pd.read_csv("../data/raw/bank-additional.csv")
df_bank.shape

(43000, 24)

In [ ]:
df_bank.head()

# Comentar que es posible utilizar .sample() y .tail() y explicarlas
# El separador es la coma, decidir si se añade a la explicación o no.

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [16]:
df_bank.columns.tolist()

['Unnamed: 0',
 'age',
 'job',
 'marital',
 'education',
 'default',
 'housing',
 'loan',
 'contact',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'poutcome',
 'emp.var.rate',
 'cons.price.idx',
 'cons.conf.idx',
 'euribor3m',
 'nr.employed',
 'y',
 'date',
 'latitude',
 'longitude',
 'id_']

In [17]:
df_bank.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  str
 3   marital         42915 non-null  str
 4   education       41193 non-null  str
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  str
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  str
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  str
 16  cons.conf.idx   43000 non-null  str
 17  euribor3m       33744 non-null  str
 18  nr.employed     43000 non-null  str
 19  y               43000 non-null  str
 20  date            42752 non-null  str
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  str
dtypes: float64(7), int64(5), str(12)
memory usage: 7.9 MB

In [18]:
df_bank.isnull().sum()

Unnamed: 0           0
age               5120
job                345
marital             85
education         1807
default           8981
housing           1026
loan              1026
contact              0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx     471
cons.conf.idx        0
euribor3m         9256
nr.employed          0
y                    0
date               248
latitude             0
longitude            0
id_                  0
dtype: int64

In [21]:
df_bank.duplicated().sum()

np.int64(0)

In [32]:
# Número de filas duplicadas

print('==========')
print('DUPLICADOS')
print() 
print(f'Número de filas duplicadas -----> {df_bank.duplicated().sum()}')
print('==========')

==========
DUPLICADOS

Número de filas duplicadas -----> 0
==========

In [33]:
df_bank["id_"].duplicated().sum()

np.int64(0)

In [34]:
df_bank.describe()

,Unnamed: 0,age,default,housing,loan,duration,campaign,pdays,previous,emp.var.rate,latitude,longitude
count,43000.000000,37880.000000,34019.000000,41974.000000,41974.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000
mean,20651.099047,39.977112,0.000088,0.535998,0.155620,257.739279,2.567233,962.330953,0.174023,0.077128,36.856697,-95.939067
std,11868.770913,10.437957,0.009390,0.498708,0.362499,258.666033,2.772294,187.260394,0.497366,1.573898,7.225948,16.752282
min,0.000000,17.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,-3.400000,24.396000,-124.997000
25%,10381.750000,32.000000,0.000000,0.000000,0.000000,102.000000,1.000000,999.000000,0.000000,-1.800000,30.614750,-110.494250
50%,20642.500000,38.000000,0.000000,1.000000,0.000000,179.000000,2.000000,999.000000,0.000000,1.100000,36.761000,-95.899500
75%,30930.250000,47.000000,0.000000,1.000000,0.000000,319.000000,3.000000,999.000000,0.000000,1.400000,43.113250,-81.427750
max,41187.000000,98.000000,1.000000,1.000000,1.000000,4918.000000,56.000000,999.000000,7.000000,1.400000,49.384000,-66.937000

In [35]:
df_bank["job"].value_counts(dropna=False)

job
admin.           10873
blue-collar       9654
technician        7026
services          4162
management        3050
retired           1790
entrepreneur      1522
self-employed     1489
housemaid         1123
unemployed        1063
student            903
NaN                345
Name: count, dtype: int64

In [36]:
columnas_texto = df_bank.select_dtypes(include="object").columns

for col in columnas_texto:
    print(f"--- {col} ---")
    print(df_bank[col].value_counts(dropna=False))
    print()

--- job ---
job
admin.           10873
blue-collar       9654
technician        7026
services          4162
management        3050
retired           1790
entrepreneur      1522
self-employed     1489
housemaid         1123
unemployed        1063
student            903
NaN                345
Name: count, dtype: int64

--- marital ---
marital
MARRIED     25999
SINGLE      12105
DIVORCED     4811
NaN            85
Name: count, dtype: int64

--- education ---
education
university.degree      12722
high.school             9925
basic.9y                6309
professional.course     5477
basic.4y                4356
basic.6y                2386
NaN                     1807
illiterate                18
Name: count, dtype: int64

--- contact ---
contact
cellular     27396
telephone    15604
Name: count, dtype: int64

--- poutcome ---
poutcome
NONEXISTENT    37103
FAILURE         4461
SUCCESS         1436
Name: count, dtype: int64

--- cons.price.idx ---
cons.price.idx
93,994    7938
93,918    6937
92,893    5985
93,444    5349
94,465    4522
93,2      3731
93,075    2552
92,201     803
92,963     742
NaN        471
92,431     471
92,649     375
94,215     320
94,199     316
92,843     298
92,379     274
93,369     271
94,027     242
94,055     236
93,876     224
94,601     212
92,469     184
92,713     179
93,749     179
94,767     130
93,798      48
92,756      11
Name: count, dtype: int64

--- cons.conf.idx ---
cons.conf.idx
-36,4    8020
-42,7    7004
-46,2    6057
-36,1    5408
-41,8    4568
-42      3782
-47,1    2581
-31,4     815
-40,8     748
-26,9     477
-30,1     379
-40,3     328
-37,5     318
-50       299
-29,8     277
-34,8     275
-38,3     245
-39,8     239
-40       225
-49,5     214
-33,6     185
-34,6     183
-33       181
-50,8     133
-40,4      48
-45,9      11
Name: count, dtype: int64

--- euribor3m ---
euribor3m
NaN      9256
4,857    2287
4,962    2124
4,963    2019
4,961    1594
         ...
0,895       1
0,894       1
0,953       1
0,956       1
1,047       1
Name: count, Length: 310, dtype: int64

--- nr.employed ---
nr.employed
5228,1    16980
5099,1     8937
5191       8020
5195,8     3830
5076,2     1748
5017,5     1133
4991,6      812
5008,7      683
4963,6      665
5023,5      181
5176,3       11
Name: count, dtype: int64

--- y ---
y
no     38156
yes     4844
Name: count, dtype: int64

--- date ---
date
NaN                  248
28-febrero-2018       95
28-febrero-2016       94
28-febrero-2015       92
28-febrero-2017       89
                    ...
16-enero-2019         11
21-diciembre-2019     10
20-noviembre-2015     10
4-abril-2017          10
14-abril-2015         10
Name: count, Length: 1826, dtype: int64

--- id_ ---
id_
089b39d8-e4d0-461b-87d4-814d71e0e079    1
e9d37224-cb6f-4942-98d7-46672963d097    1
3f9f49b5-e410-4948-bf6e-f9244f04918b    1
9991fafb-4447-451a-8be2-b0df6098d13e    1
eca60b76-70b6-4077-80ba-bc52e8ebb0eb    1
                                       ..
4eed05de-2a98-4227-b488-32122009b638    1
0f0aca88-4088-4fe2-905f-44fb675d9493    1
cadadd4b-7ee5-4019-b13a-ca01bb67ca5b    1
5f432048-d515-4bb5-9c94-62db451f88d4    1
993bbbd6-4dbc-4a40-a408-f91f8462bee6    1
Name: count, Length: 43000, dtype: int64

C:\Users\Hp\AppData\Local\Temp\ipykernel_29888\2411680293.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columnas_texto = df_bank.select_dtypes(include="object").columns

In [37]:
df_bank[["latitude", "longitude"]].describe()

           latitude     longitude
count  43000.000000  43000.000000
mean      36.856697    -95.939067
std        7.225948     16.752282
min       24.396000   -124.997000
25%       30.614750   -110.494250
50%       36.761000    -95.899500
75%       43.113250    -81.427750
max       49.384000    -66.937000

In [38]:
excel = pd.ExcelFile("../data/raw/customer-details.xlsx")
excel.sheet_names

['2012', '2013', '2014']

In [39]:
hojas = {nombre: pd.read_excel(excel, sheet_name=nombre) for nombre in excel.sheet_names}

for nombre, hoja in hojas.items():
    print(f"--- Hoja: {nombre} | Filas: {hoja.shape[0]} | Columnas: {hoja.shape[1]} ---")

--- Hoja: 2012 | Filas: 20115 | Columnas: 7 ---
--- Hoja: 2013 | Filas: 8965 | Columnas: 7 ---
--- Hoja: 2014 | Filas: 14090 | Columnas: 7 ---

In [40]:
for nombre, hoja in hojas.items():
    print(nombre, hoja.columns.tolist())

2012 ['Unnamed: 0', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth', 'ID']
2013 ['Unnamed: 0', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth', 'ID']
2014 ['Unnamed: 0', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth', 'ID']

In [41]:
primera = hojas[excel.sheet_names[0]]
primera.info()

<class 'pandas.DataFrame'>
RangeIndex: 20115 entries, 0 to 20114
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         20115 non-null  int64
 1   Income             20115 non-null  int64
 2   Kidhome            20115 non-null  int64
 3   Teenhome           20115 non-null  int64
 4   Dt_Customer        20115 non-null  datetime64[us]
 5   NumWebVisitsMonth  20115 non-null  int64
 6   ID                 20115 non-null  str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.1 MB

In [42]:
primera.isnull().sum()

Unnamed: 0           0
Income               0
Kidhome              0
Teenhome             0
Dt_Customer          0
NumWebVisitsMonth    0
ID                   0
dtype: int64

In [43]:
primera.describe()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
count,20115.000000,20115.000000,20115.000000,20115.000000,20115,20115.000000
mean,10057.000000,93087.213224,1.004176,0.999503,2012-07-01 17:15:14.362416,16.540790
min,0.000000,5852.000000,0.000000,0.000000,2012-01-01 00:00:00,1.000000
25%,5028.500000,49110.000000,0.000000,0.000000,2012-04-01 00:00:00,9.000000
50%,10057.000000,92962.000000,1.000000,1.000000,2012-07-02 00:00:00,16.000000
75%,15085.500000,136705.000000,2.000000,2.000000,2012-09-30 00:00:00,25.000000
max,20114.000000,180791.000000,2.000000,2.000000,2012-12-31 00:00:00,32.000000
std,5806.844668,50614.798255,0.816811,0.815298,NaN,9.235324

In [44]:
primera[["ID", "Dt_Customer"]].head()

                                     ID Dt_Customer
0  089b39d8-e4d0-461b-87d4-814d71e0e079  2012-04-04
1  e9d37224-cb6f-4942-98d7-46672963d097  2012-12-30
2  3f9f49b5-e410-4948-bf6e-f9244f04918b  2012-02-02
3  9991fafb-4447-451a-8be2-b0df6098d13e  2012-12-21
4  eca60b76-70b6-4077-80ba-bc52e8ebb0eb  2012-06-20

In [45]:
# Une las 3 hojas temporalmente solo para esta comprobación
df_clientes = pd.concat(hojas.values(), ignore_index=True)

print("Filas CSV:", df_bank.shape[0])
print("Filas Excel (3 hojas):", df_clientes.shape[0])

ids_bank = set(df_bank["id_"])
ids_clientes = set(df_clientes["ID"])

print("IDs en común:", len(ids_bank & ids_clientes))
print("IDs solo en CSV:", len(ids_bank - ids_clientes))
print("IDs solo en Excel:", len(ids_clientes - ids_bank))

Filas CSV: 43000
Filas Excel (3 hojas): 43170
IDs en común: 43000
IDs solo en CSV: 0
IDs solo en Excel: 170

In [46]:
df_bank.drop(columns="Unnamed: 0").duplicated().sum()

np.int64(0)

In [47]:
(df_bank["Unnamed: 0"] == df_bank.index).all()

np.False_

In [48]:
df_bank["Unnamed: 0"].head(10)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: Unnamed: 0, dtype: int64

In [49]:
cols_texto_num = ["cons.price.idx", "cons.conf.idx", "euribor3m", "nr.employed"]
df_bank[cols_texto_num].head(10)

  cons.price.idx cons.conf.idx euribor3m nr.employed
0         93,994         -36,4     4,857        5191
1         93,994         -36,4       NaN        5191
2         93,994         -36,4     4,857        5191
3         93,994         -36,4       NaN        5191
4         93,994         -36,4       NaN        5191
5         93,994         -36,4     4,857        5191
6         93,994         -36,4     4,857        5191
7         93,994         -36,4     4,857        5191
8         93,994         -36,4     4,857        5191
9         93,994         -36,4       NaN        5191

In [50]:
for col in cols_texto_num:
    convertido = pd.to_numeric(df_bank[col], errors="coerce")
    problemas = df_bank.loc[convertido.isnull() & df_bank[col].notnull(), col]
    print(f"--- {col}: {len(problemas)} valores no convertibles ---")
    print(problemas.value_counts().head())

--- cons.price.idx: 42529 valores no convertibles ---
cons.price.idx
93,994    7938
93,918    6937
92,893    5985
93,444    5349
94,465    4522
Name: count, dtype: int64
--- cons.conf.idx: 38513 valores no convertibles ---
cons.conf.idx
-36,4    8020
-42,7    7004
-46,2    6057
-36,1    5408
-41,8    4568
Name: count, dtype: int64
--- euribor3m: 33729 valores no convertibles ---
euribor3m
4,857    2287
4,962    2124
4,963    2019
4,961    1594
4,964     964
Name: count, dtype: int64
--- nr.employed: 34980 valores no convertibles ---
nr.employed
5228,1    16980
5099,1     8937
5195,8     3830
5076,2     1748
5017,5     1133
Name: count, dtype: int64

In [51]:
(df_bank["housing"].isnull() == df_bank["loan"].isnull()).all()

np.True_

In [52]:
df_bank[["id_", "date"]].head(10)

                                    id_                date
0  089b39d8-e4d0-461b-87d4-814d71e0e079       2-agosto-2019
1  e9d37224-cb6f-4942-98d7-46672963d097  14-septiembre-2016
2  3f9f49b5-e410-4948-bf6e-f9244f04918b     15-febrero-2019
3  9991fafb-4447-451a-8be2-b0df6098d13e   29-noviembre-2015
4  eca60b76-70b6-4077-80ba-bc52e8ebb0eb       29-enero-2017
5  d63ede72-0b6d-45b1-8872-385ac6897f65  26-septiembre-2015
6  5e3483e5-236d-437d-8351-541f9d09b9dd       25-enero-2019
7  87fdc08b-30ae-4dab-803f-561ecdf27ff0  25-septiembre-2017
8  87b79988-2be5-419d-88f4-56655852c565       18-enero-2018
9  ea6b7d04-9271-4c0a-a01f-07795d164aba    2-noviembre-2016

In [53]:
# 1. ¿Unnamed: 0 tiene valores repetidos?
df_bank["Unnamed: 0"].duplicated().sum()

np.int64(1968)

In [54]:
# 2. Valores de default, housing, loan
for col in ["default", "housing", "loan"]:
    print(df_bank[col].value_counts(dropna=False))

default
0.0    34016
NaN     8981
1.0        3
Name: count, dtype: int64
housing
1.0    22498
0.0    19476
NaN     1026
Name: count, dtype: int64
loan
0.0    35442
1.0     6532
NaN     1026
Name: count, dtype: int64

In [55]:
# 3. Cuántos duration == 0, y cuántos age > 90
print((df_bank["duration"] == 0).sum())
print((df_bank["age"] > 90).sum())

4
10

In [56]:
# 4. Excel: info y nulos de la hoja 2012
primera = hojas["2012"]
primera.info()
print(primera.isnull().sum())
print(primera.describe())
print(primera[["ID", "Dt_Customer"]].head())

<class 'pandas.DataFrame'>
RangeIndex: 20115 entries, 0 to 20114
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         20115 non-null  int64
 1   Income             20115 non-null  int64
 2   Kidhome            20115 non-null  int64
 3   Teenhome           20115 non-null  int64
 4   Dt_Customer        20115 non-null  datetime64[us]
 5   NumWebVisitsMonth  20115 non-null  int64
 6   ID                 20115 non-null  str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.1 MB
Unnamed: 0           0
Income               0
Kidhome              0
Teenhome             0
Dt_Customer          0
NumWebVisitsMonth    0
ID                   0
dtype: int64
         Unnamed: 0         Income       Kidhome      Teenhome  \
count  20115.000000   20115.000000  20115.000000  20115.000000
mean   10057.000000   93087.213224      1.004176      0.999503
min        0.000000    5852.000000      0.000000      0.000000
25%     5028.500000   49110.000000      0.000000      0.000000
50%    10057.000000   92962.000000      1.000000      1.000000
75%    15085.500000  136705.000000      2.000000      2.000000
max    20114.000000  180791.000000      2.000000      2.000000
std     5806.844668   50614.798255      0.816811      0.815298

                      Dt_Customer  NumWebVisitsMonth
count                       20115       20115.000000
mean   2012-07-01 17:15:14.362416          16.540790
min           2012-01-01 00:00:00           1.000000
25%           2012-04-01 00:00:00           9.000000
50%           2012-07-02 00:00:00          16.000000
75%           2012-09-30 00:00:00          25.000000
max           2012-12-31 00:00:00          32.000000
std                           NaN           9.235324
                                     ID Dt_Customer
0  089b39d8-e4d0-461b-87d4-814d71e0e079  2012-04-04
1  e9d37224-cb6f-4942-98d7-46672963d097  2012-12-30
2  3f9f49b5-e410-4948-bf6e-f9244f04918b  2012-02-02
3  9991fafb-4447-451a-8be2-b0df6098d13e  2012-12-21
4  eca60b76-70b6-4077-80ba-bc52e8ebb0eb  2012-06-20

In [57]:
# 5. Excel: IDs duplicados en el conjunto de 3 hojas
df_clientes["ID"].duplicated().sum()

np.int64(0)

In [58]:
for nombre, hoja in hojas.items():
    print(nombre, "| nulos:", hoja.isnull().sum().sum(),
          "| fechas:", hoja["Dt_Customer"].min().date(), "->", hoja["Dt_Customer"].max().date())

2012 | nulos: 0 | fechas: 2012-01-01 -> 2012-12-31
2013 | nulos: 0 | fechas: 2013-01-01 -> 2013-12-31
2014 | nulos: 0 | fechas: 2014-01-01 -> 2014-12-31

## Problemas detectados en la inspección inicial

### CSV (`bank-additional.csv`): 43.000 filas, 24 columnas

**Estructura y columnas**
- Columna extra `Unnamed: 0` no descrita en el enunciado. No coincide con el índice y tiene 1.968 valores repetidos, por lo que no sirve como identificador. **Decisión:** eliminar.
- Nombres de columnas con puntos (`emp.var.rate`, `cons.price.idx`, `cons.conf.idx`, `nr.employed`) e `id_` con guion bajo final. **Decisión:** renombrar a formato limpio.

**Tipos de datos**
- `cons.price.idx`, `cons.conf.idx`, `euribor3m` y `nr.employed` están como texto porque usan **coma decimal** (ej. `93,994`). **Decisión:** reemplazar `,` por `.` y convertir a número.
- `date` está como texto y **en español** (ej. `2-agosto-2019`). **Decisión:** traducir los meses con un diccionario y convertir con `to_datetime`.
- `age`, `default`, `housing` y `loan` son `float64` por los nulos. **Decisión:** corregir tras tratar los nulos.

**Nulos**
| Columna | Nulos | % aprox. |
|---|---|---|
| euribor3m | 9.256 | 21,5 % |
| default | 8.981 | 20,9 % |
| age | 5.120 | 11,9 % |
| education | 1.807 | 4,2 % |
| housing | 1.026 | 2,4 % |
| loan | 1.026 | 2,4 % |
| cons.price.idx | 471 | 1,1 % |
| job | 345 | 0,8 % |
| date | 248 | 0,6 % |
| marital | 85 | 0,2 % |

- `housing` y `loan` tienen nulos **en las mismas filas** (comprobado).

**Duplicados**
- 0 duplicados completos (también sin contar `Unnamed: 0`).
- 0 duplicados por `id_`.

**Valores especiales y atípicos**
- `pdays = 999` en más del 75 % de las filas (significa "no contactado antes"). **Decisión:** crear `contactado_antes` y tratar 999 como nulo.
- `default`: 34.016 ceros, solo **3 unos** y 8.981 nulos. Sin variabilidad útil. **Decisión:** excluir del análisis y justificarlo en el informe.
- `duration = 0` en 4 filas. **Decisión:** conservar y anotar.
- `campaign` con máximo 56 (cola larga). **Decisión:** revisar outliers en la Sesión 4.
- `age` mínimo 17 y máximo 98; 10 casos con más de 90 años. **Decisión:** conservar (valores posibles).
- `age` tiene 11,9 % de nulos. **Decisión:** definir tratamiento en la Sesión 4.

**Inconsistencias en categorías**
- `marital` y `poutcome` están en MAYÚSCULAS; el resto de columnas de texto, en minúsculas. **Decisión:** unificar a minúsculas.
- `education` incluye `illiterate` con solo 18 casos. **Decisión:** conservar o agrupar (a decidir).
- No se detectan valores tipo `unknown`, `?` o espacios en blanco; los vacíos son `NaN`.

**Variable objetivo**
- `y` solo toma `yes` / `no`, pero está **desbalanceada**: 4.844 `yes` (≈11,3 %) frente a 38.156 `no`. Se mencionará en el informe.
- `duration` solo se conoce después de la llamada: sirve para describir, no para predecir.

**Latitud y longitud**
- Rangos: latitud 24,4 a 49,4 y longitud -125,0 a -66,9, que corresponden a **Estados Unidos**, no a Portugal. Incoherente con el enunciado. **Decisión:** no usar como análisis geográfico de Portugal y anotar la incoherencia en el informe.

### Excel (`customer-details.xlsx`): 3 hojas

| Hoja | Filas | Columnas | Nulos | Rango de `Dt_Customer` |
|---|---|---|---|---|
| 2012 | 20.115 | 7 | 0 | 2012-01-01 → 2012-12-31 |
| 2013 | 8.965 | 7 | 0 | 2013-01-01 → 2013-12-31 |
| 2014 | 14.090 | 7 | 0 | 2014-01-01 → 2014-12-31 |
| **Total** | **43.170** | | | |

- Las 3 hojas tienen **las mismas columnas**, por lo que se pueden concatenar.
- También incluyen una columna `Unnamed: 0`. **Decisión:** eliminar.
- `Dt_Customer` ya viene como fecha y cada hoja coincide con su año.
- `Income` entre 5.852 y 180.791, sin nulos ni atípicos claros (revisado en la hoja 2012).
- `Kidhome` y `Teenhome` toman valores 0, 1 y 2.
- `NumWebVisitsMonth` hasta 32, con distribución casi uniforme (posible dato sintético; no sobreinterpretar).
- 0 `ID` duplicados entre las 3 hojas.

### Compatibilidad entre datasets
- IDs en común: **43.000**
- IDs solo en el CSV: **0**
- IDs solo en el Excel: **170**
- **Decisión:** unión `left` desde el CSV. Resultado esperado: 43.000 filas.
- Las fechas del Excel (2012-2014) son anteriores a las del CSV (2015-2019), lo que permite calcular la **antigüedad del cliente**.

### Resumen de decisiones para la Sesión 3
1. Eliminar `Unnamed: 0` (CSV y Excel).
2. Concatenar las 3 hojas del Excel.
3. Renombrar columnas a formato limpio.
4. Convertir a número las 4 columnas con coma decimal.
5. Traducir y convertir `date` a fecha.
6. Pasar `marital` y `poutcome` a minúsculas.
7. Excluir `default` del análisis.
8. Tratar `pdays = 999` y crear `contactado_antes`.
9. Unir con `left` y validar que quedan 43.000 filas.